### ISSUE TITLE
Maintained/Will it work?

### ISSUE THREAD

**Issue by TechStudent10** [interactions-py/voice#10]
I saw the notice in the README, tried the install command and checked the issues. It looks like this is an unfinished, unmaintained project. Is this the case?

**Comment by i0bs** [comment]
This repo will be defunct upon the launch of v5. When this happens, the repository will either be archived, deleted and/or made private. For now, you are able to use this with v4.

**Comment by TechStudent10** [comment]
> This repo will be defunct upon the launch of v5. When this happens, the repository will either be archived, deleted and/or made private. For now, you are able to use this with v4.

Will v5 have voice builtin?

**Comment by Damego** [comment]
Yeah

**Comment by TechStudent10** [comment]
Alright, thanks. You should probably change the install command to the git pip install version.

**Comment by Damego** [comment]
This extension was merged into library in v4.4.0. I think we will just delete this repository
