### ISSUE TITLE
HTTPClient.__init__() missing 1 required positional argument: 'cache'

### ISSUE THREAD

**Issue by Flixl09** [interactions-py/voice#11]
I wanted to use the Voice Client with the "setup()" function, but it seems to fail every time, because the HTTP Request is not working. I looked through the HTTPClient.__init__() function and there was no cache parameter in there!

**Comment by Damego** [comment]
This extension was merged into library in v4.4.0.
Also this extension is outdated because maintainer left and will be removed soon

**Comment by Flixl09** [comment]
So i just have to update the interactions-py library and it should work?

**Comment by Damego** [comment]
There is no `VoiceClient` class. All features (`voice state update` event listening) now in the library

**Comment by AstreaTSS** [comment]
At this point, this should be a help thread, not an issue. Feel free to join the interactions.py server for help!

Also, yeah, closing this.
