### ISSUE TITLE
Receiving audio

### ISSUE THREAD

**Issue by KohnoseLami** [interactions-py/voice#4]
You cannot currently receive audio with discord.py.
The best solution for receiving audio is to use the JavaScript discord.js.
I love the nice interactions.py, but it lacks audio features
That's when I discovered this extension.
Is it possible to receive audio when using this?
I want to make VC recording function in Bot.

Also, the documentation installation method is incorrect
```
PS D:\Desktop\Projects\NX> pip install -U interactions-voice
ERROR: Could not find a version that satisfies the requirement interactions-voice (from versions: none)
ERROR: No matching distribution found for interactions-voice
```

**Comment by EdVraz** [comment]
Hi ^^

This lib is still a WIP, so I haven't published to pypi yet. Because of that, neither playing music nor listening to music is possible atm. I'll have a look at listening tho

**Comment by KohnoseLami** [comment]
Oh, sorry!
OK, I'm looking forward to the completion of this module!
